

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Fill : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass>
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Fill()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Fill(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Fill> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Fill.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fill_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fill_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string OrderStatus
        {
            get
            {
                return global::LightSwitchApplication.Fill.DetailsClass.GetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.OrderStatus);
            }
            set
            {
                global::LightSwitchApplication.Fill.DetailsClass.SetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.OrderStatus, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderStatus_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderStatus_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderStatus_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double AvgPx
        {
            get
            {
                return global::LightSwitchApplication.Fill.DetailsClass.GetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.AvgPx);
            }
            set
            {
                global::LightSwitchApplication.Fill.DetailsClass.SetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.AvgPx, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AvgPx_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AvgPx_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AvgPx_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double LeavesQty
        {
            get
            {
                return global::LightSwitchApplication.Fill.DetailsClass.GetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.LeavesQty);
            }
            set
            {
                global::LightSwitchApplication.Fill.DetailsClass.SetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.LeavesQty, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LeavesQty_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LeavesQty_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LeavesQty_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CumQty
        {
            get
            {
                return global::LightSwitchApplication.Fill.DetailsClass.GetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.CumQty);
            }
            set
            {
                global::LightSwitchApplication.Fill.DetailsClass.SetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.CumQty, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CumQty_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CumQty_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CumQty_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public long Ticks
        {
            get
            {
                return global::LightSwitchApplication.Fill.DetailsClass.GetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.Ticks);
            }
            set
            {
                global::LightSwitchApplication.Fill.DetailsClass.SetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.Ticks, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Ticks_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Ticks_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Ticks_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ExecReport
        {
            get
            {
                return global::LightSwitchApplication.Fill.DetailsClass.GetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.ExecReport);
            }
            set
            {
                global::LightSwitchApplication.Fill.DetailsClass.SetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.ExecReport, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExecReport_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExecReport_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExecReport_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double FillQty
        {
            get
            {
                return global::LightSwitchApplication.Fill.DetailsClass.GetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.FillQty);
            }
            set
            {
                global::LightSwitchApplication.Fill.DetailsClass.SetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.FillQty, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FillQty_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FillQty_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FillQty_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double LastPx
        {
            get
            {
                return global::LightSwitchApplication.Fill.DetailsClass.GetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.LastPx);
            }
            set
            {
                global::LightSwitchApplication.Fill.DetailsClass.SetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.LastPx, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastPx_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastPx_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastPx_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string OrderID
        {
            get
            {
                return global::LightSwitchApplication.Fill.DetailsClass.GetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.OrderID);
            }
            set
            {
                global::LightSwitchApplication.Fill.DetailsClass.SetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.OrderID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Identity
        {
            get
            {
                return global::LightSwitchApplication.Fill.DetailsClass.GetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.Identity);
            }
            set
            {
                global::LightSwitchApplication.Fill.DetailsClass.SetValue(this, global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.Identity, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Identity_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Identity_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Identity_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Fill,
                global::LightSwitchApplication.Fill.DetailsClass,
                global::LightSwitchApplication.Fill.DetailsClass.IImplementation,
                global::LightSwitchApplication.Fill.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.OrderStatus;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass>.Entry
                __FillEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass>.Entry(
                    global::LightSwitchApplication.Fill.DetailsClass.__Fill_CreateNew,
                    global::LightSwitchApplication.Fill.DetailsClass.__Fill_Created,
                    global::LightSwitchApplication.Fill.DetailsClass.__Fill_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Fill __Fill_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Fill> es)
            {
                return new global::LightSwitchApplication.Fill(es);
            }
            private static void __Fill_Created(global::LightSwitchApplication.Fill e)
            {
                e.Fill_Created();
            }
            private static bool __Fill_AllowSaveWithErrors(global::LightSwitchApplication.Fill e)
            {
                bool result = false;
                e.Fill_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Fill.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string> OrderStatus
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.OrderStatus) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double> AvgPx
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.AvgPx) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double> LeavesQty
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.LeavesQty) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double> CumQty
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.CumQty) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, long> Ticks
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.Ticks) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, long>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string> ExecReport
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.ExecReport) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double> FillQty
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.FillQty) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double> LastPx
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.LastPx) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string> OrderID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.OrderID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string> Identity
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties.Identity) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new string OrderStatus { get; set; }
                new double AvgPx { get; set; }
                new double LeavesQty { get; set; }
                new double CumQty { get; set; }
                new long Ticks { get; set; }
                new string ExecReport { get; set; }
                new double FillQty { get; set; }
                new double LastPx { get; set; }
                new string OrderID { get; set; }
                new string Identity { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>.Entry
                    OrderStatus = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>.Entry(
                        "OrderStatus",
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._OrderStatus_Stub,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._OrderStatus_ComputeIsReadOnly,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._OrderStatus_Validate,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._OrderStatus_GetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._OrderStatus_SetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._OrderStatus_OnValueChanged);
                private static void _OrderStatus_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Fill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>.Data> c, global::LightSwitchApplication.Fill.DetailsClass d, object sf)
                {
                    c(d, ref d._OrderStatus, sf);
                }
                private static bool _OrderStatus_ComputeIsReadOnly(global::LightSwitchApplication.Fill e)
                {
                    bool result = false;
                    e.OrderStatus_IsReadOnly(ref result);
                    return result;
                }
                private static void _OrderStatus_Validate(global::LightSwitchApplication.Fill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.OrderStatus_Validate(r);
                }
                private static string _OrderStatus_GetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d)
                {
                    return d.ImplementationEntity.OrderStatus;
                }
                private static void _OrderStatus_SetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d, string v)
                {
                    d.ImplementationEntity.OrderStatus = v;
                }
                private static void _OrderStatus_OnValueChanged(global::LightSwitchApplication.Fill e)
                {
                    e.OrderStatus_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Entry
                    AvgPx = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Entry(
                        "AvgPx",
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._AvgPx_Stub,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._AvgPx_ComputeIsReadOnly,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._AvgPx_Validate,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._AvgPx_GetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._AvgPx_SetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._AvgPx_OnValueChanged);
                private static void _AvgPx_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Fill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Data> c, global::LightSwitchApplication.Fill.DetailsClass d, object sf)
                {
                    c(d, ref d._AvgPx, sf);
                }
                private static bool _AvgPx_ComputeIsReadOnly(global::LightSwitchApplication.Fill e)
                {
                    bool result = false;
                    e.AvgPx_IsReadOnly(ref result);
                    return result;
                }
                private static void _AvgPx_Validate(global::LightSwitchApplication.Fill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.AvgPx_Validate(r);
                }
                private static double _AvgPx_GetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d)
                {
                    return d.ImplementationEntity.AvgPx;
                }
                private static void _AvgPx_SetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d, double v)
                {
                    d.ImplementationEntity.AvgPx = v;
                }
                private static void _AvgPx_OnValueChanged(global::LightSwitchApplication.Fill e)
                {
                    e.AvgPx_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Entry
                    LeavesQty = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Entry(
                        "LeavesQty",
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._LeavesQty_Stub,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._LeavesQty_ComputeIsReadOnly,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._LeavesQty_Validate,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._LeavesQty_GetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._LeavesQty_SetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._LeavesQty_OnValueChanged);
                private static void _LeavesQty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Fill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Data> c, global::LightSwitchApplication.Fill.DetailsClass d, object sf)
                {
                    c(d, ref d._LeavesQty, sf);
                }
                private static bool _LeavesQty_ComputeIsReadOnly(global::LightSwitchApplication.Fill e)
                {
                    bool result = false;
                    e.LeavesQty_IsReadOnly(ref result);
                    return result;
                }
                private static void _LeavesQty_Validate(global::LightSwitchApplication.Fill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LeavesQty_Validate(r);
                }
                private static double _LeavesQty_GetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d)
                {
                    return d.ImplementationEntity.LeavesQty;
                }
                private static void _LeavesQty_SetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d, double v)
                {
                    d.ImplementationEntity.LeavesQty = v;
                }
                private static void _LeavesQty_OnValueChanged(global::LightSwitchApplication.Fill e)
                {
                    e.LeavesQty_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Entry
                    CumQty = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Entry(
                        "CumQty",
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._CumQty_Stub,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._CumQty_ComputeIsReadOnly,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._CumQty_Validate,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._CumQty_GetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._CumQty_SetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._CumQty_OnValueChanged);
                private static void _CumQty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Fill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Data> c, global::LightSwitchApplication.Fill.DetailsClass d, object sf)
                {
                    c(d, ref d._CumQty, sf);
                }
                private static bool _CumQty_ComputeIsReadOnly(global::LightSwitchApplication.Fill e)
                {
                    bool result = false;
                    e.CumQty_IsReadOnly(ref result);
                    return result;
                }
                private static void _CumQty_Validate(global::LightSwitchApplication.Fill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CumQty_Validate(r);
                }
                private static double _CumQty_GetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d)
                {
                    return d.ImplementationEntity.CumQty;
                }
                private static void _CumQty_SetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d, double v)
                {
                    d.ImplementationEntity.CumQty = v;
                }
                private static void _CumQty_OnValueChanged(global::LightSwitchApplication.Fill e)
                {
                    e.CumQty_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, long>.Entry
                    Ticks = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, long>.Entry(
                        "Ticks",
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._Ticks_Stub,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._Ticks_ComputeIsReadOnly,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._Ticks_Validate,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._Ticks_GetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._Ticks_SetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._Ticks_OnValueChanged);
                private static void _Ticks_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Fill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, long>.Data> c, global::LightSwitchApplication.Fill.DetailsClass d, object sf)
                {
                    c(d, ref d._Ticks, sf);
                }
                private static bool _Ticks_ComputeIsReadOnly(global::LightSwitchApplication.Fill e)
                {
                    bool result = false;
                    e.Ticks_IsReadOnly(ref result);
                    return result;
                }
                private static void _Ticks_Validate(global::LightSwitchApplication.Fill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Ticks_Validate(r);
                }
                private static long _Ticks_GetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d)
                {
                    return d.ImplementationEntity.Ticks;
                }
                private static void _Ticks_SetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d, long v)
                {
                    d.ImplementationEntity.Ticks = v;
                }
                private static void _Ticks_OnValueChanged(global::LightSwitchApplication.Fill e)
                {
                    e.Ticks_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>.Entry
                    ExecReport = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>.Entry(
                        "ExecReport",
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._ExecReport_Stub,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._ExecReport_ComputeIsReadOnly,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._ExecReport_Validate,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._ExecReport_GetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._ExecReport_SetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._ExecReport_OnValueChanged);
                private static void _ExecReport_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Fill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>.Data> c, global::LightSwitchApplication.Fill.DetailsClass d, object sf)
                {
                    c(d, ref d._ExecReport, sf);
                }
                private static bool _ExecReport_ComputeIsReadOnly(global::LightSwitchApplication.Fill e)
                {
                    bool result = false;
                    e.ExecReport_IsReadOnly(ref result);
                    return result;
                }
                private static void _ExecReport_Validate(global::LightSwitchApplication.Fill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ExecReport_Validate(r);
                }
                private static string _ExecReport_GetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d)
                {
                    return d.ImplementationEntity.ExecReport;
                }
                private static void _ExecReport_SetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ExecReport = v;
                }
                private static void _ExecReport_OnValueChanged(global::LightSwitchApplication.Fill e)
                {
                    e.ExecReport_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Entry
                    FillQty = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Entry(
                        "FillQty",
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._FillQty_Stub,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._FillQty_ComputeIsReadOnly,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._FillQty_Validate,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._FillQty_GetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._FillQty_SetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._FillQty_OnValueChanged);
                private static void _FillQty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Fill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Data> c, global::LightSwitchApplication.Fill.DetailsClass d, object sf)
                {
                    c(d, ref d._FillQty, sf);
                }
                private static bool _FillQty_ComputeIsReadOnly(global::LightSwitchApplication.Fill e)
                {
                    bool result = false;
                    e.FillQty_IsReadOnly(ref result);
                    return result;
                }
                private static void _FillQty_Validate(global::LightSwitchApplication.Fill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FillQty_Validate(r);
                }
                private static double _FillQty_GetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d)
                {
                    return d.ImplementationEntity.FillQty;
                }
                private static void _FillQty_SetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d, double v)
                {
                    d.ImplementationEntity.FillQty = v;
                }
                private static void _FillQty_OnValueChanged(global::LightSwitchApplication.Fill e)
                {
                    e.FillQty_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Entry
                    LastPx = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Entry(
                        "LastPx",
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._LastPx_Stub,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._LastPx_ComputeIsReadOnly,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._LastPx_Validate,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._LastPx_GetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._LastPx_SetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._LastPx_OnValueChanged);
                private static void _LastPx_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Fill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Data> c, global::LightSwitchApplication.Fill.DetailsClass d, object sf)
                {
                    c(d, ref d._LastPx, sf);
                }
                private static bool _LastPx_ComputeIsReadOnly(global::LightSwitchApplication.Fill e)
                {
                    bool result = false;
                    e.LastPx_IsReadOnly(ref result);
                    return result;
                }
                private static void _LastPx_Validate(global::LightSwitchApplication.Fill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LastPx_Validate(r);
                }
                private static double _LastPx_GetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d)
                {
                    return d.ImplementationEntity.LastPx;
                }
                private static void _LastPx_SetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d, double v)
                {
                    d.ImplementationEntity.LastPx = v;
                }
                private static void _LastPx_OnValueChanged(global::LightSwitchApplication.Fill e)
                {
                    e.LastPx_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>.Entry
                    OrderID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>.Entry(
                        "OrderID",
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._OrderID_Stub,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._OrderID_ComputeIsReadOnly,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._OrderID_Validate,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._OrderID_GetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._OrderID_SetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._OrderID_OnValueChanged);
                private static void _OrderID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Fill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>.Data> c, global::LightSwitchApplication.Fill.DetailsClass d, object sf)
                {
                    c(d, ref d._OrderID, sf);
                }
                private static bool _OrderID_ComputeIsReadOnly(global::LightSwitchApplication.Fill e)
                {
                    bool result = false;
                    e.OrderID_IsReadOnly(ref result);
                    return result;
                }
                private static void _OrderID_Validate(global::LightSwitchApplication.Fill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.OrderID_Validate(r);
                }
                private static string _OrderID_GetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d)
                {
                    return d.ImplementationEntity.OrderID;
                }
                private static void _OrderID_SetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d, string v)
                {
                    d.ImplementationEntity.OrderID = v;
                }
                private static void _OrderID_OnValueChanged(global::LightSwitchApplication.Fill e)
                {
                    e.OrderID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>.Entry
                    Identity = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>.Entry(
                        "Identity",
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._Identity_Stub,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._Identity_ComputeIsReadOnly,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._Identity_Validate,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._Identity_GetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._Identity_SetImplementationValue,
                        global::LightSwitchApplication.Fill.DetailsClass.PropertySetProperties._Identity_OnValueChanged);
                private static void _Identity_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Fill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>.Data> c, global::LightSwitchApplication.Fill.DetailsClass d, object sf)
                {
                    c(d, ref d._Identity, sf);
                }
                private static bool _Identity_ComputeIsReadOnly(global::LightSwitchApplication.Fill e)
                {
                    bool result = false;
                    e.Identity_IsReadOnly(ref result);
                    return result;
                }
                private static void _Identity_Validate(global::LightSwitchApplication.Fill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Identity_Validate(r);
                }
                private static string _Identity_GetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d)
                {
                    return d.ImplementationEntity.Identity;
                }
                private static void _Identity_SetImplementationValue(global::LightSwitchApplication.Fill.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Identity = v;
                }
                private static void _Identity_OnValueChanged(global::LightSwitchApplication.Fill e)
                {
                    e.Identity_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>.Data _OrderStatus;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Data _AvgPx;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Data _LeavesQty;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Data _CumQty;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, long>.Data _Ticks;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>.Data _ExecReport;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Data _FillQty;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, double>.Data _LastPx;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>.Data _OrderID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Fill, global::LightSwitchApplication.Fill.DetailsClass, string>.Data _Identity;
            
        }
    
        #endregion
    }
    
    #endregion
}
