

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class User : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public User()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public User(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.User> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.User.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void User_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void User_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Enabled
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Enabled);
            }
            set
            {
                global::LightSwitchApplication.User.DetailsClass.SetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Enabled, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Enabled_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Enabled_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Enabled_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ID
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.ID);
            }
            set
            {
                global::LightSwitchApplication.User.DetailsClass.SetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.ID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string UserPwd
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.UserPwd);
            }
            set
            {
                global::LightSwitchApplication.User.DetailsClass.SetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.UserPwd, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserPwd_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserPwd_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserPwd_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string UserID
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.UserID);
            }
            set
            {
                global::LightSwitchApplication.User.DetailsClass.SetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.UserID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string K2Config
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.K2Config);
            }
            set
            {
                global::LightSwitchApplication.User.DetailsClass.SetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.K2Config, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void K2Config_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void K2Config_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void K2Config_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.User,
                global::LightSwitchApplication.User.DetailsClass,
                global::LightSwitchApplication.User.DetailsClass.IImplementation,
                global::LightSwitchApplication.User.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Enabled;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>.Entry
                __UserEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>.Entry(
                    global::LightSwitchApplication.User.DetailsClass.__User_CreateNew,
                    global::LightSwitchApplication.User.DetailsClass.__User_Created,
                    global::LightSwitchApplication.User.DetailsClass.__User_AllowSaveWithErrors);
            private static global::LightSwitchApplication.User __User_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.User> es)
            {
                return new global::LightSwitchApplication.User(es);
            }
            private static void __User_Created(global::LightSwitchApplication.User e)
            {
                e.User_Created();
            }
            private static bool __User_AllowSaveWithErrors(global::LightSwitchApplication.User e)
            {
                bool result = false;
                e.User_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.User.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, bool> Enabled
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Enabled) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string> ID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.ID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string> UserPwd
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.UserPwd) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string> UserID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.UserID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string> K2Config
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.K2Config) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new bool Enabled { get; set; }
                new string ID { get; set; }
                new string UserPwd { get; set; }
                new string UserID { get; set; }
                new string K2Config { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, bool>.Entry
                    Enabled = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, bool>.Entry(
                        "Enabled",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Enabled_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Enabled_ComputeIsReadOnly,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Enabled_Validate,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Enabled_GetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Enabled_SetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Enabled_OnValueChanged);
                private static void _Enabled_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, bool>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._Enabled, sf);
                }
                private static bool _Enabled_ComputeIsReadOnly(global::LightSwitchApplication.User e)
                {
                    bool result = false;
                    e.Enabled_IsReadOnly(ref result);
                    return result;
                }
                private static void _Enabled_Validate(global::LightSwitchApplication.User e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Enabled_Validate(r);
                }
                private static bool _Enabled_GetImplementationValue(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.Enabled;
                }
                private static void _Enabled_SetImplementationValue(global::LightSwitchApplication.User.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.Enabled = v;
                }
                private static void _Enabled_OnValueChanged(global::LightSwitchApplication.User e)
                {
                    e.Enabled_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry
                    ID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry(
                        "ID",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._ID_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._ID_Validate,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._ID_GetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._ID_SetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._ID_OnValueChanged);
                private static void _ID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._ID, sf);
                }
                private static bool _ID_ComputeIsReadOnly(global::LightSwitchApplication.User e)
                {
                    bool result = false;
                    e.ID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Validate(global::LightSwitchApplication.User e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Validate(r);
                }
                private static string _ID_GetImplementationValue(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.ID;
                }
                private static void _ID_SetImplementationValue(global::LightSwitchApplication.User.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ID = v;
                }
                private static void _ID_OnValueChanged(global::LightSwitchApplication.User e)
                {
                    e.ID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry
                    UserPwd = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry(
                        "UserPwd",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._UserPwd_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._UserPwd_ComputeIsReadOnly,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._UserPwd_Validate,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._UserPwd_GetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._UserPwd_SetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._UserPwd_OnValueChanged);
                private static void _UserPwd_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._UserPwd, sf);
                }
                private static bool _UserPwd_ComputeIsReadOnly(global::LightSwitchApplication.User e)
                {
                    bool result = false;
                    e.UserPwd_IsReadOnly(ref result);
                    return result;
                }
                private static void _UserPwd_Validate(global::LightSwitchApplication.User e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UserPwd_Validate(r);
                }
                private static string _UserPwd_GetImplementationValue(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.UserPwd;
                }
                private static void _UserPwd_SetImplementationValue(global::LightSwitchApplication.User.DetailsClass d, string v)
                {
                    d.ImplementationEntity.UserPwd = v;
                }
                private static void _UserPwd_OnValueChanged(global::LightSwitchApplication.User e)
                {
                    e.UserPwd_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry
                    UserID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry(
                        "UserID",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._UserID_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._UserID_ComputeIsReadOnly,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._UserID_Validate,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._UserID_GetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._UserID_SetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._UserID_OnValueChanged);
                private static void _UserID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._UserID, sf);
                }
                private static bool _UserID_ComputeIsReadOnly(global::LightSwitchApplication.User e)
                {
                    bool result = false;
                    e.UserID_IsReadOnly(ref result);
                    return result;
                }
                private static void _UserID_Validate(global::LightSwitchApplication.User e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UserID_Validate(r);
                }
                private static string _UserID_GetImplementationValue(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.UserID;
                }
                private static void _UserID_SetImplementationValue(global::LightSwitchApplication.User.DetailsClass d, string v)
                {
                    d.ImplementationEntity.UserID = v;
                }
                private static void _UserID_OnValueChanged(global::LightSwitchApplication.User e)
                {
                    e.UserID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry
                    K2Config = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry(
                        "K2Config",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._K2Config_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._K2Config_ComputeIsReadOnly,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._K2Config_Validate,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._K2Config_GetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._K2Config_SetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._K2Config_OnValueChanged);
                private static void _K2Config_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._K2Config, sf);
                }
                private static bool _K2Config_ComputeIsReadOnly(global::LightSwitchApplication.User e)
                {
                    bool result = false;
                    e.K2Config_IsReadOnly(ref result);
                    return result;
                }
                private static void _K2Config_Validate(global::LightSwitchApplication.User e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.K2Config_Validate(r);
                }
                private static string _K2Config_GetImplementationValue(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.K2Config;
                }
                private static void _K2Config_SetImplementationValue(global::LightSwitchApplication.User.DetailsClass d, string v)
                {
                    d.ImplementationEntity.K2Config = v;
                }
                private static void _K2Config_OnValueChanged(global::LightSwitchApplication.User e)
                {
                    e.K2Config_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, bool>.Data _Enabled;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data _ID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data _UserPwd;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data _UserID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data _K2Config;
            
        }
    
        #endregion
    }
    
    #endregion
}
