

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Account : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass>
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Account()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Account(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Account> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Account.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Account_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Account_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Code
        {
            get
            {
                return global::LightSwitchApplication.Account.DetailsClass.GetValue(this, global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties.Code);
            }
            set
            {
                global::LightSwitchApplication.Account.DetailsClass.SetValue(this, global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties.Code, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Code_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Code_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Code_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LongName
        {
            get
            {
                return global::LightSwitchApplication.Account.DetailsClass.GetValue(this, global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties.LongName);
            }
            set
            {
                global::LightSwitchApplication.Account.DetailsClass.SetValue(this, global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties.LongName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LongName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LongName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LongName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FirmCode
        {
            get
            {
                return global::LightSwitchApplication.Account.DetailsClass.GetValue(this, global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties.FirmCode);
            }
            set
            {
                global::LightSwitchApplication.Account.DetailsClass.SetValue(this, global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties.FirmCode, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirmCode_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirmCode_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirmCode_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Identity
        {
            get
            {
                return global::LightSwitchApplication.Account.DetailsClass.GetValue(this, global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties.Identity);
            }
            set
            {
                global::LightSwitchApplication.Account.DetailsClass.SetValue(this, global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties.Identity, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Identity_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Identity_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Identity_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string VenueCode
        {
            get
            {
                return global::LightSwitchApplication.Account.DetailsClass.GetValue(this, global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties.VenueCode);
            }
            set
            {
                global::LightSwitchApplication.Account.DetailsClass.SetValue(this, global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties.VenueCode, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VenueCode_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VenueCode_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VenueCode_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Account,
                global::LightSwitchApplication.Account.DetailsClass,
                global::LightSwitchApplication.Account.DetailsClass.IImplementation,
                global::LightSwitchApplication.Account.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties.Code;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass>.Entry
                __AccountEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass>.Entry(
                    global::LightSwitchApplication.Account.DetailsClass.__Account_CreateNew,
                    global::LightSwitchApplication.Account.DetailsClass.__Account_Created,
                    global::LightSwitchApplication.Account.DetailsClass.__Account_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Account __Account_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Account> es)
            {
                return new global::LightSwitchApplication.Account(es);
            }
            private static void __Account_Created(global::LightSwitchApplication.Account e)
            {
                e.Account_Created();
            }
            private static bool __Account_AllowSaveWithErrors(global::LightSwitchApplication.Account e)
            {
                bool result = false;
                e.Account_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Account.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string> Code
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties.Code) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string> LongName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties.LongName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string> FirmCode
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties.FirmCode) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string> Identity
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties.Identity) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string> VenueCode
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties.VenueCode) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new string Code { get; set; }
                new string LongName { get; set; }
                new string FirmCode { get; set; }
                new string Identity { get; set; }
                new string VenueCode { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Entry
                    Code = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Entry(
                        "Code",
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._Code_Stub,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._Code_ComputeIsReadOnly,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._Code_Validate,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._Code_GetImplementationValue,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._Code_SetImplementationValue,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._Code_OnValueChanged);
                private static void _Code_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Account.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Data> c, global::LightSwitchApplication.Account.DetailsClass d, object sf)
                {
                    c(d, ref d._Code, sf);
                }
                private static bool _Code_ComputeIsReadOnly(global::LightSwitchApplication.Account e)
                {
                    bool result = false;
                    e.Code_IsReadOnly(ref result);
                    return result;
                }
                private static void _Code_Validate(global::LightSwitchApplication.Account e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Code_Validate(r);
                }
                private static string _Code_GetImplementationValue(global::LightSwitchApplication.Account.DetailsClass d)
                {
                    return d.ImplementationEntity.Code;
                }
                private static void _Code_SetImplementationValue(global::LightSwitchApplication.Account.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Code = v;
                }
                private static void _Code_OnValueChanged(global::LightSwitchApplication.Account e)
                {
                    e.Code_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Entry
                    LongName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Entry(
                        "LongName",
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._LongName_Stub,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._LongName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._LongName_Validate,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._LongName_GetImplementationValue,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._LongName_SetImplementationValue,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._LongName_OnValueChanged);
                private static void _LongName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Account.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Data> c, global::LightSwitchApplication.Account.DetailsClass d, object sf)
                {
                    c(d, ref d._LongName, sf);
                }
                private static bool _LongName_ComputeIsReadOnly(global::LightSwitchApplication.Account e)
                {
                    bool result = false;
                    e.LongName_IsReadOnly(ref result);
                    return result;
                }
                private static void _LongName_Validate(global::LightSwitchApplication.Account e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LongName_Validate(r);
                }
                private static string _LongName_GetImplementationValue(global::LightSwitchApplication.Account.DetailsClass d)
                {
                    return d.ImplementationEntity.LongName;
                }
                private static void _LongName_SetImplementationValue(global::LightSwitchApplication.Account.DetailsClass d, string v)
                {
                    d.ImplementationEntity.LongName = v;
                }
                private static void _LongName_OnValueChanged(global::LightSwitchApplication.Account e)
                {
                    e.LongName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Entry
                    FirmCode = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Entry(
                        "FirmCode",
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._FirmCode_Stub,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._FirmCode_ComputeIsReadOnly,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._FirmCode_Validate,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._FirmCode_GetImplementationValue,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._FirmCode_SetImplementationValue,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._FirmCode_OnValueChanged);
                private static void _FirmCode_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Account.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Data> c, global::LightSwitchApplication.Account.DetailsClass d, object sf)
                {
                    c(d, ref d._FirmCode, sf);
                }
                private static bool _FirmCode_ComputeIsReadOnly(global::LightSwitchApplication.Account e)
                {
                    bool result = false;
                    e.FirmCode_IsReadOnly(ref result);
                    return result;
                }
                private static void _FirmCode_Validate(global::LightSwitchApplication.Account e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FirmCode_Validate(r);
                }
                private static string _FirmCode_GetImplementationValue(global::LightSwitchApplication.Account.DetailsClass d)
                {
                    return d.ImplementationEntity.FirmCode;
                }
                private static void _FirmCode_SetImplementationValue(global::LightSwitchApplication.Account.DetailsClass d, string v)
                {
                    d.ImplementationEntity.FirmCode = v;
                }
                private static void _FirmCode_OnValueChanged(global::LightSwitchApplication.Account e)
                {
                    e.FirmCode_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Entry
                    Identity = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Entry(
                        "Identity",
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._Identity_Stub,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._Identity_ComputeIsReadOnly,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._Identity_Validate,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._Identity_GetImplementationValue,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._Identity_SetImplementationValue,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._Identity_OnValueChanged);
                private static void _Identity_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Account.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Data> c, global::LightSwitchApplication.Account.DetailsClass d, object sf)
                {
                    c(d, ref d._Identity, sf);
                }
                private static bool _Identity_ComputeIsReadOnly(global::LightSwitchApplication.Account e)
                {
                    bool result = false;
                    e.Identity_IsReadOnly(ref result);
                    return result;
                }
                private static void _Identity_Validate(global::LightSwitchApplication.Account e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Identity_Validate(r);
                }
                private static string _Identity_GetImplementationValue(global::LightSwitchApplication.Account.DetailsClass d)
                {
                    return d.ImplementationEntity.Identity;
                }
                private static void _Identity_SetImplementationValue(global::LightSwitchApplication.Account.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Identity = v;
                }
                private static void _Identity_OnValueChanged(global::LightSwitchApplication.Account e)
                {
                    e.Identity_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Entry
                    VenueCode = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Entry(
                        "VenueCode",
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._VenueCode_Stub,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._VenueCode_ComputeIsReadOnly,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._VenueCode_Validate,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._VenueCode_GetImplementationValue,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._VenueCode_SetImplementationValue,
                        global::LightSwitchApplication.Account.DetailsClass.PropertySetProperties._VenueCode_OnValueChanged);
                private static void _VenueCode_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Account.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Data> c, global::LightSwitchApplication.Account.DetailsClass d, object sf)
                {
                    c(d, ref d._VenueCode, sf);
                }
                private static bool _VenueCode_ComputeIsReadOnly(global::LightSwitchApplication.Account e)
                {
                    bool result = false;
                    e.VenueCode_IsReadOnly(ref result);
                    return result;
                }
                private static void _VenueCode_Validate(global::LightSwitchApplication.Account e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.VenueCode_Validate(r);
                }
                private static string _VenueCode_GetImplementationValue(global::LightSwitchApplication.Account.DetailsClass d)
                {
                    return d.ImplementationEntity.VenueCode;
                }
                private static void _VenueCode_SetImplementationValue(global::LightSwitchApplication.Account.DetailsClass d, string v)
                {
                    d.ImplementationEntity.VenueCode = v;
                }
                private static void _VenueCode_OnValueChanged(global::LightSwitchApplication.Account e)
                {
                    e.VenueCode_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Data _Code;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Data _LongName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Data _FirmCode;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Data _Identity;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Account, global::LightSwitchApplication.Account.DetailsClass, string>.Data _VenueCode;
            
        }
    
        #endregion
    }
    
    #endregion
}
