CREATE TABLE [dbo].[Strategy] (
    [LastOrdIdentity]   NVARCHAR (255)  NULL,
    [UserID]            NVARCHAR (36)   NULL,
    [SessionID]         NVARCHAR (36)   NULL,
    [Identity]          NVARCHAR (36)   NOT NULL,
    [AutoCreate]        BIT             NOT NULL,
    [ProductID]         NVARCHAR (36)   NULL,
    [Mnemonic]          NVARCHAR (256)  NULL,
    [DataMnemonic]      NVARCHAR (256)  NULL,
    [Side]              NVARCHAR (1)    NULL,
    [ShortSaleLocate]   NVARCHAR (256)  NULL,
    [OrdType]           NVARCHAR (1)    NULL,
    [TimeInForce]       NVARCHAR (26)   NULL,
    [TIFDateTime]       NVARCHAR (26)   NULL,
    [QtyLimit]          FLOAT           NOT NULL,
    [MaxIterations]     INT             NOT NULL,
    [MaxEntries]        INT             NOT NULL,
    [MaxPrice]          FLOAT           NOT NULL,
    [MinPrice]          FLOAT           NOT NULL,
    [Qty]               FLOAT           NOT NULL,
    [MaxFloor]          FLOAT           NULL,
    [Price]             FLOAT           NOT NULL,
    [FlattenOnExit]     BIT             NOT NULL,
    [CancelOnExit]      BIT             NOT NULL,
    [UseStrategyTimes]  BIT             NOT NULL,
    [StartTime]         DATETIME        NOT NULL,
    [EndTime]           DATETIME        NOT NULL,
    [UserName]          NVARCHAR (256)  NULL,
    [StopPx]            FLOAT           NOT NULL,
    [Account]           NVARCHAR (256)  NULL,
    [Type]              INT             NOT NULL,
    [PXAlgorithmName]   NVARCHAR (256)  NULL,
    [TriggerName]       NVARCHAR (256)  NULL,
    [EntryTriggerName]  NVARCHAR (256)  NULL,
    [ExitTriggerName]   NVARCHAR (256)  NULL,
    [AutoConnectTrg]    BIT             NOT NULL,
    [ConditionInterval] INT             NOT NULL,
    [Enabled]           BIT             NOT NULL,
    [ORAlgorithmName]   NVARCHAR (256)  NULL,
    [ParameterBag]      NVARCHAR (4000) NULL,
    [RunIdentifier]     NVARCHAR (256)  NULL,
    [CorrelationID]     NVARCHAR (256)  NULL,
    [TSQueryGroupPath]  NVARCHAR (1024) NULL,
    [Info]              NVARCHAR (512)  NULL,
    [State]             INT             NOT NULL,
    [Initialized]       BIT             NOT NULL
);

