ALTER TABLE [dbo].[Product]
    ADD CONSTRAINT [PK_dbo.Product] PRIMARY KEY CLUSTERED ([Mnemonic] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

