//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace BarDataTools {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.kaitrade.com/KA")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.kaitrade.com/KA", IsNullable=false)]
    public partial class TSQueryGroup {
        
        private TSQueryGroupTSDataSet[] tSDataSetField;
        
        private string nameField;
        
        private string mnemonicField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TSDataSet")]
        public TSQueryGroupTSDataSet[] TSDataSet {
            get {
                return this.tSDataSetField;
            }
            set {
                this.tSDataSetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Mnemonic {
            get {
                return this.mnemonicField;
            }
            set {
                this.mnemonicField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.kaitrade.com/KA")]
    public partial class TSQueryGroupTSDataSet {
        
        private TSQueryGroupTSDataSetTSExpression tSExpressionField;
        
        private string mnemonicField;
        
        private string identityField;
        
        private string nameField;
        
        private byte tSTypeField;
        
        private string aliasField;
        
        private byte sessionFlagsField;
        
        private string conditionNameField;
        
        private string studyNameField;
        
        private byte periodField;
        
        private byte rangeTypeField;
        
        private System.DateTime startTimeField;
        
        private System.DateTime endTimeField;
        
        private byte intStartField;
        
        private sbyte intEndField;
        
        private byte intraDayIntervalField;
        
        private bool includeEndField;
        
        private bool updatesEnabledField;
        
        private string textField;
        
        private byte sessionFilterField;
        
        private byte tSVolumeTypeField;
        
        private bool tSVolumeTypeFieldSpecified;
        
        private byte volumeLevelField;
        
        private bool volumeLevelFieldSpecified;
        
        private bool includeFlatTicksField;
        
        private bool includeFlatTicksFieldSpecified;
        
        private string strategyNameField;
        
        private bool autoCreateStrategyField;
        
        private bool autoCreateStrategyFieldSpecified;
        
        /// <remarks/>
        public TSQueryGroupTSDataSetTSExpression TSExpression {
            get {
                return this.tSExpressionField;
            }
            set {
                this.tSExpressionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Mnemonic {
            get {
                return this.mnemonicField;
            }
            set {
                this.mnemonicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identity {
            get {
                return this.identityField;
            }
            set {
                this.identityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte TSType {
            get {
                return this.tSTypeField;
            }
            set {
                this.tSTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte SessionFlags {
            get {
                return this.sessionFlagsField;
            }
            set {
                this.sessionFlagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ConditionName {
            get {
                return this.conditionNameField;
            }
            set {
                this.conditionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StudyName {
            get {
                return this.studyNameField;
            }
            set {
                this.studyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte RangeType {
            get {
                return this.rangeTypeField;
            }
            set {
                this.rangeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte IntStart {
            get {
                return this.intStartField;
            }
            set {
                this.intStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte IntEnd {
            get {
                return this.intEndField;
            }
            set {
                this.intEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte IntraDayInterval {
            get {
                return this.intraDayIntervalField;
            }
            set {
                this.intraDayIntervalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IncludeEnd {
            get {
                return this.includeEndField;
            }
            set {
                this.includeEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool UpdatesEnabled {
            get {
                return this.updatesEnabledField;
            }
            set {
                this.updatesEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte SessionFilter {
            get {
                return this.sessionFilterField;
            }
            set {
                this.sessionFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte TSVolumeType {
            get {
                return this.tSVolumeTypeField;
            }
            set {
                this.tSVolumeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TSVolumeTypeSpecified {
            get {
                return this.tSVolumeTypeFieldSpecified;
            }
            set {
                this.tSVolumeTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte VolumeLevel {
            get {
                return this.volumeLevelField;
            }
            set {
                this.volumeLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VolumeLevelSpecified {
            get {
                return this.volumeLevelFieldSpecified;
            }
            set {
                this.volumeLevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IncludeFlatTicks {
            get {
                return this.includeFlatTicksField;
            }
            set {
                this.includeFlatTicksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncludeFlatTicksSpecified {
            get {
                return this.includeFlatTicksFieldSpecified;
            }
            set {
                this.includeFlatTicksFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StrategyName {
            get {
                return this.strategyNameField;
            }
            set {
                this.strategyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AutoCreateStrategy {
            get {
                return this.autoCreateStrategyField;
            }
            set {
                this.autoCreateStrategyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AutoCreateStrategySpecified {
            get {
                return this.autoCreateStrategyFieldSpecified;
            }
            set {
                this.autoCreateStrategyFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.kaitrade.com/KA")]
    public partial class TSQueryGroupTSDataSetTSExpression {
        
        private string expressionField;
        
        private string aliasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Expression {
            get {
                return this.expressionField;
            }
            set {
                this.expressionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
    }
}
