<?xml version="1.0" encoding="utf-8"?><Database Name="K2DS" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.1.11.15;Initial Catalog=K2DS;Integrated Security=True" SettingsObjectName="K2DS.Properties.Settings" SettingsPropertyName="K2DSConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PriceBar" Member="PriceBars">
    <Type Name="PriceBar">
      <Column Name="Mnemonic" Type="System.String" DbType="NVarChar(256) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Period" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ticks" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="High" Type="System.Decimal" DbType="Decimal(18,6) NOT NULL" CanBeNull="false" />
      <Column Name="Low" Type="System.Decimal" DbType="Decimal(18,6) NOT NULL" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Decimal" DbType="Decimal(18,6) NOT NULL" CanBeNull="false" />
      <Column Name="[Close]" Member="Close" Type="System.Decimal" DbType="Decimal(18,6) NOT NULL" CanBeNull="false" />
      <Column Name="Avg" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
</Database>