CREATE TABLE [dbo].[Trade] (
    [Identity]            NVARCHAR (36)  NULL,
    [TradeID]             NVARCHAR (256) NOT NULL,
    [MatchID]             NVARCHAR (256) NULL,
    [MessageEventSource]  NVARCHAR (256) NULL,
    [TradingSessionID]    NVARCHAR (256) NULL,
    [TradeInputSource]    NVARCHAR (256) NULL,
    [HandlInst]           NVARCHAR (256) NULL,
    [VenueType]           NVARCHAR (256) NULL,
    [ExecutingBrokerCode] NVARCHAR (255) NULL,
    [ClearingBrokerCode]  NVARCHAR (256) NULL,
    [Trader]              NVARCHAR (256) NULL,
    [ClearingDate]        NVARCHAR (26)  NULL,
    [BusinessDate]        NVARCHAR (26)  NULL,
    [SessionID]           NVARCHAR (256) NULL,
    [SessionSubID]        NVARCHAR (256) NULL,
    [VenueCode]           NVARCHAR (256) NULL,
    [ProductID]           NVARCHAR (36)  NULL,
    [Mnemonic]            NVARCHAR (256) NULL,
    [Account]             NVARCHAR (256) NULL,
    [ClOrdID]             NVARCHAR (256) NULL,
    [ClOrdID2]            NVARCHAR (256) NULL,
    [OrigClOrdID]         NVARCHAR (256) NULL,
    [OrderID]             NVARCHAR (256) NULL,
    [Side]                NVARCHAR (32)  NULL,
    [OrdType]             NVARCHAR (32)  NULL,
    [Quantity]            FLOAT          NULL,
    [Price]               FLOAT          NULL,
    [StopPx]              FLOAT          NULL,
    [TradeStatus]         NVARCHAR (32)  NULL,
    [LeavesQty]           FLOAT          NULL,
    [CumQty]              FLOAT          NULL,
    [LastPx]              FLOAT          NULL,
    [LastQty]             FLOAT          NULL,
    [AvgPx]               FLOAT          NULL,
    [Text]                NVARCHAR (512) NULL,
    [TransactTime]        NVARCHAR (26)  NULL,
    [TradeDate]           NVARCHAR (26)  NULL,
    [Description]         NVARCHAR (256) NULL,
    [Tag]                 NVARCHAR (512) NULL,
    [CorrelationID]       NVARCHAR (256) NULL,
    [ExecutionID]         NVARCHAR (256) NULL,
    [TimeInForce]         NVARCHAR (26)  NULL,
    [PositionEffect]      NVARCHAR (1)   NULL,
    [SystemDate]          DATETIME       NOT NULL
);

