ALTER TABLE [dbo].[PlugIn]
    ADD CONSTRAINT [PK_dbo.PlugIn] PRIMARY KEY CLUSTERED ([Identity] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

