ALTER TABLE [dbo].[Exchange]
    ADD CONSTRAINT [PK_dbo.Exchange] PRIMARY KEY CLUSTERED ([ExchangeCode] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

