ALTER TABLE [dbo].[Trade]
    ADD CONSTRAINT [PK_dbo.Trade] PRIMARY KEY CLUSTERED ([TradeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

