ALTER TABLE [dbo].[Extension]
    ADD CONSTRAINT [PK_dbo.Extension] PRIMARY KEY CLUSTERED ([SrcIdentity] ASC, [AssetIdentity] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

