ALTER TABLE [dbo].[Firm]
    ADD CONSTRAINT [PK_dbo.Firm] PRIMARY KEY CLUSTERED ([FirmCode] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

