CREATE TABLE [dbo].[Product] (
    [CFICode]                     NVARCHAR (16)   NULL,
    [Currency]                    NVARCHAR (3)    NULL,
    [DriverID]                    NVARCHAR (255)  NULL,
    [Exchange]                    NVARCHAR (255)  NULL,
    [IDSource]                    NVARCHAR (255)  NULL,
    [Identity]                    NVARCHAR (255)  NULL,
    [LongName]                    NVARCHAR (512)  NULL,
    [Commodity]                   NVARCHAR (255)  NULL,
    [MMY]                         NVARCHAR (32)   NULL,
    [GenericName]                 NVARCHAR (255)  NULL,
    [Mnemonic]                    NVARCHAR (255)  NOT NULL,
    [QtyIncrement]                INT             NOT NULL,
    [SecurityID]                  NVARCHAR (255)  NULL,
    [StrikePrice]                 DECIMAL (29, 4) NULL,
    [Symbol]                      NVARCHAR (255)  NULL,
    [Tag]                         NVARCHAR (512)  NULL,
    [TickSize]                    DECIMAL (29, 4) NULL,
    [TickValue]                   DECIMAL (29, 4) NULL,
    [NumberDecimalPlaces]         INT             NOT NULL,
    [PriceFeedQuantityMultiplier] INT             NOT NULL,
    [ContractSize]                DECIMAL (29, 4) NULL,
    [TradeVenue]                  NVARCHAR (255)  NULL,
    [BrokerService]               NVARCHAR (255)  NULL,
    [ExDestination]               NVARCHAR (255)  NULL,
    [DepthLevelCount]             INT             NOT NULL,
    [SyntheticPriceCalcName]      NVARCHAR (255)  NULL
);

