CREATE TABLE [dbo].[Trade] (
    [Identity]            NVARCHAR (255) NULL,
    [TradeID]             NVARCHAR (255) NOT NULL,
    [MatchID]             NVARCHAR (255) NULL,
    [MessageEventSource]  NVARCHAR (255) NULL,
    [TradingSessionID]    NVARCHAR (255) NULL,
    [TradeInputSource]    NVARCHAR (255) NULL,
    [HandlInst]           NVARCHAR (255) NULL,
    [VenueType]           NVARCHAR (255) NULL,
    [ExecutingBrokerCode] NVARCHAR (255) NULL,
    [ClearingBrokerCode]  NVARCHAR (255) NULL,
    [Trader]              NVARCHAR (255) NULL,
    [ClearingDate]        NVARCHAR (255) NULL,
    [BusinessDate]        NVARCHAR (64)  NULL,
    [SessionID]           NVARCHAR (255) NULL,
    [SessionSubID]        NVARCHAR (255) NULL,
    [VenueCode]           NVARCHAR (255) NULL,
    [ProductID]           NVARCHAR (255) NULL,
    [Src]                 NVARCHAR (255) NULL,
    [IDSrc]               NVARCHAR (255) NULL,
    [Sym]                 NVARCHAR (255) NULL,
    [Exch]                NVARCHAR (255) NULL,
    [MMY]                 NVARCHAR (32)  NULL,
    [Strk]                NVARCHAR (32)  NULL,
    [CFI]                 NVARCHAR (16)  NULL,
    [Mnemonic]            NVARCHAR (255) NULL,
    [Account]             NVARCHAR (255) NULL,
    [ClOrdID]             NVARCHAR (512) NULL,
    [OrigClOrdID]         NVARCHAR (512) NULL,
    [OrderID]             NVARCHAR (255) NULL,
    [Side]                NVARCHAR (255) NULL,
    [OrdType]             NVARCHAR (255) NULL,
    [Quantity]            NVARCHAR (255) NULL,
    [Price]               FLOAT          NULL,
    [StopPx]              FLOAT          NULL,
    [OrdStatus]           NVARCHAR (255) NULL,
    [LeavesQty]           FLOAT          NULL,
    [CumQty]              FLOAT          NULL,
    [LastPx]              FLOAT          NULL,
    [LastQty]             FLOAT          NULL,
    [AvgPx]               FLOAT          NULL,
    [Text]                NVARCHAR (512) NULL,
    [TransactTime]        NVARCHAR (64)  NULL,
    [Description]         NVARCHAR (255) NULL,
    [Tag]                 NVARCHAR (512) NULL,
    [CorrelationID]       NVARCHAR (255) NULL,
    [ExecutionID]         NVARCHAR (255) NULL,
    [TimeInForce]         NVARCHAR (255) NULL,
    [PositionEffect]      NVARCHAR (255) NULL
);

